site_name: Qognito.io
site_description: L'Ingénierie de l'Intelligence Physique pour systèmes critiques.

theme:
  name: material
  language: fr
  palette:
    # Mode sombre (Navy profond)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: amber
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: amber
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md

# Configuration des couleurs personnalisées (Titanium & Navy)
extra:
  colors:
    primary: "#0A1628" 
    accent: "#D4850F"
